[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip = ["./src/example/test_goto.py", "./src/example/test_mobile_base.py"]

[tool.black]
line-length = 128