[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip = ["./tests/integration/test_goto.py", "./tests/integration/test_mobile_base.py"]

[tool.black]
line-length = 128