name: Generate Python Documentation

on: [pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Generate Documentation
      run: pdoc reachy2_sdk --output-dir docs --logo "https://pollen-robotics.github.io/reachy2-sdk/POLLEN_LOGO.png" --logo-link "https://www.pollen-robotics.com"

    - name: Archive Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/

  publish-docs:
    needs: build-docs
    runs-on: ubuntu-22.04
    steps:
      - name: Download Documentation
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/
            
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs